@startuml

interface AuthService {
    +auth()
    +checkToken()
}

interface AccountService {
    +getAthlets()
    +getTrainers()
    +getReferees()
    +getCompetitions()
    +updateAccount()
}

interface AthletService {
    +getOwnCompetitions()
    +getResults()
    +updateFields()
}

interface TrainerService {
    +getOwnAthlets()
    +getAthletResults()
    +updateFields()
}

interface RefereeService {
    +getOwnCompetitions()
    +updateFields()
}

interface CompetitionService {
    +create()
    +update()
    +delete()
    +filter()
    +syncBattles()
    +addBattle()
}

CompetitionService ..> CompetitionSyncService

interface ResultsService {
    +resultScore()
    +resultsByGroupService()
}

interface CompetitionSyncService {
    +getCompetition()
}

@enduml