@startuml component

package "Слой доступа к данным" {
    [компонент доступа к данным]
    [компонент доступа к данным] -- Postgres
    [компонент доступа к данным] -- MongoDB
}

package "Слой бизнес-логики" {
    [компонент бизнес-логики]
}

package "Слой доставки" {
    [компонент реализации интерфейса] -- HTTP
}

[компонент реализации интерфейса] <--> [компонент бизнес-логики]
[компонент бизнес-логики] <--> [компонент доступа к данным]

@enduml