@startuml systemEntities

entity Пользователь {
    ID 
    IDRole
    Логин 
    Телефон 
    ФИО
}

entity Соревнование {
    ID
    Дата
    Возрастая категория
    Тип оружия
    Вид
    Тип
}

entity Бой {
    ID
    ID победителя
    ID проигравшего
    Счет победителя
    Счет проишравшего
}

entity Спортсмен {
    ID
    День рождения
    Тип оружия
    Пол
    Субъект РФ
    Вооруженная рука
    Лицензия
    Страховка
}

@enduml