@startuml usecase

left to right direction

:Гость: --> (Авторизация)

:Спортсмен: --> (Просмотр профиля)
:Спортсмен: --> (Просмотр результатов \n соревнований)
:Спортсмен: --> (Просмотр календаря \n соревнований)

(Просмотр календаря \n соревнований) --> (Фильтрация данных)

(Просмотр профиля) --> (Редактирование информации)
(Просмотр профиля) --> (Выход из системы)

' :Тренер: --> :Спортсмен:
' :Тренер: --> (Просмотр карточек \n своих спортсменов)
' :Тренер: --> (Просмотр результатов \n соревнований)
' :Тренер: --> (Просмотр календаря \n соревнований)

' :Судья: --> :Спортсмен:
' :Судья: --> (Просмотр календаря \n соревнований)

:Модератор: --> (Загрузка информации \n о соревнованиях)
:Модератор: --> (Загрузка информации \n о спортсменах)
:Модератор: --> (Загрузка информации \n о тренерах)
:Модератор: --> (Загрузка информации \n о судьях)
:Модератор: --> (Редактирование информации \n о соревнованиях)
:Модератор: --> :Спортсмен:

(Редактирование информации \n о соревнованиях) --> (Редактирование соревнования)
(Редактирование информации \n о соревнованиях) --> (Создание соревнования)
(Редактирование информации \n о соревнованиях) --> (Удаление соревнования)

@enduml
